# Use postgres/example user/password credentials
version: '3.7'

services:
  django:
    build: .
    container_name: django
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:latest
    restart: always
    container_name: container_bd
    hostname: myhost
    environment:
      POSTGRES_DB: bdprueba
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
  
  pgadmin:
    image: dpage/pgadmin4
    environment: 
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin1234
    ports:
        - '5051:80'
    restart: always
    volumes: 
         - ~/Documentos/Docker_vol/Vol_DJango1/pgadmin:/root/.pgadmin